[api]
url = "https://script.google.com/macros/s/AKfycbzooNuvpe5TvlTxjO41wezeWczepkqoYTyIsX37KhGtT2vuKG1tiHVkRJntPZpoNOrcLw/exec"  # your web app /exec URL
token = "YYKGwxZtu3d-I6-aupg1OQCgnYfA1aE7pXStNTprx0qERzgEwFMzA4KpBMJlEwqd"                      # same as API_TOKEN
form_url = "https://script.google.com/macros/s/AKfycbzooNuvpe5TvlTxjO41wezeWczepkqoYTyIsX37KhGtT2vuKG1tiHVkRJntPZpoNOrcLw/exec"  # your web app /exec URL