[api]
url = "https://script.google.com/macros/s/AKfycbzrpVfKjdAHfemCXltaeB3a6oRn4lvmr3AJYPn466x8kxhytbFyRr1wk08OTBmNw32YRA/exec"  # your web app /exec URL
token = "YYKGwxZtu3d-I6-aupg1OQCgnYfA1aE7pXStNTprx0qERzgEwFMzA4KpBMJlEwqd"                      # same as API_TOKEN
form_url = "https://script.google.com/macros/s/AKfycbzrpVfKjdAHfemCXltaeB3a6oRn4lvmr3AJYPn466x8kxhytbFyRr1wk08OTBmNw32YRA/exec"  # your web app /exec URL