locations: [Classroom, Hallway, Cafeteria, Playground, Bus, Other]
antecedents: [Task demand, Transition, Peer conflict, Attention shift, Unstructured time, Other]
behaviors: [Disruption (loud), Elopement, Noncompliance, Physical aggression, Property destruction, Self-injury, Verbal aggression, Other]
consequences: [Attention (adult/peer), Escape/avoid task, Tangible access, Sensory/automatic, Planned ignore, Time-out, Office referral, Other]
interventions: [Prompting, Break card, First/Then, Token, Calming corner]
