# === global ===
form_url = "https://script.google.com/macros/s/AKfycbzrpVfKjdAHfemCXltaeB3a6oRn4lvmr3AJYPn466x8kxhytbFyRr1wk08OTBmNw32YRA/exec"

# === Incidents / Trends API ===
[api]
url   = "https://script.google.com/macros/s/AKfycbzrpVfKjdAHfemCXltaeB3a6oRn4lvmr3AJYPn466x8kxhytbFyRr1wk08OTBmNw32YRA/exec"
token = "YYKGwxZtu3d-I6-aupg1OQCgnYfA1aE7pXStNTprx0qERzgEwFMzA4KpBMJlEwqd"

# === Frequency API (students + events) ===
[freq_api]
url   = "https://script.google.com/macros/s/AKfycbyouxYK3x1Fxd-zysjIl0t25c4kEQu_X1FJMP68U4VYQOV3hr7K9BtiP2xKYN8cxW5Y_g/exec"
token = "frequency"

# === Interventions API (catalog/assignments/tracking) ===
[interv_api]
url   = "https://script.google.com/macros/s/AKfycbzrX4qu71mqxkMj37vum1KTepHKE6tk5_KAccUfwfBDB8JfScdYfE8Lft4Xi9MfJH0SaQ/exec"
token = "token"